/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "App_Config.h"
#include "FreeRTOS.h"
#include "task.h"

#include "Service/CpuGeneric/SysSe/Bsp/Bsp.h"

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
typedef struct a {
        int a;
        int b;
} _a;
typedef struct b {
        int a;
        int b;
} _b;
int func1(int, int, int, int);
struct a func2(_a, _b);
struct a func3(_a, _b);

int func1(int a, int b, int c, int d)
{
    _a a1;
    _b b1;
    int r;

    if(a <= 10) {
        r = func1(c, d, a, b);
    }
    else if(a <= 20) {
        r = func1(d, c, b, a);
    }
    else {
        a1.a = a;
        a1.b = b;
        b1.a = c;
        b1.b = d;
        a1 = func2(a1, b1);
    }
    return r;
}
struct a func2(struct a a1, struct b b1)
{
        struct a ret;
        ret.a = a1.a + b1.a;
        ret.b = - a1.b - b1.b;
        ret = func3(ret, b1);
        return ret;
}
struct a func3(struct a a1, struct b b1)
{
        struct a ret;
        ret.a = a1.a + b1.a;
        ret.b = a1.b + b1.b;
        return ret;
}

volatile int a, b, c, d;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    IfxPort_setPinMode(GPIO_P33_10.port, GPIO_P33_10.pinIndex, IfxPort_Mode_outputPushPullGeneral);
    /* Create LED1 app task */
    xTaskCreate(task_app_led1, "APP LED1", configMINIMAL_STACK_SIZE, NULL, 0, NULL);

    /* Create LED2 app task */
    xTaskCreate(task_app_led2, "APP LED2", configMINIMAL_STACK_SIZE, NULL, 0, NULL);

    /* Start the scheduler */
    vTaskStartScheduler();
    while(1) {
        int a = func1(a, b, c, d);
    }

//    /* LED test without OS */
//    IfxPort_setPinMode(LED_1.port, LED_1.pinIndex, IfxPort_Mode_outputPushPullGeneral);
//    IfxPort_setPinMode(LED_2.port, LED_2.pinIndex, IfxPort_Mode_outputPushPullGeneral);
//    while(1)
//    {
//        IfxPort_setPinState(LED_1.port, LED_1.pinIndex, IfxPort_State_toggled);
//        IfxPort_setPinState(LED_2.port, LED_2.pinIndex, IfxPort_State_toggled);
//        // Wait for 1000 milliseconds
//        uint32_t waitTicks = IfxStm_getTicksFromMilliseconds(&MODULE_STM0, 1000);
//        wait(waitTicks);
//    }
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;

    while (1)
    {
        // You can put a breakpoint here
    }
}

volatile uint32_t g_tickCount = 0;
void __attribute__((used, noinline)) vApplicationTickHook(void)
{
    g_tickCount++;
}

